const PRODUCTS=[{"name": "Essential Cotton Boxer Briefs (3-Pack)", "category": "boxers", "price": "$39.99", "description": "Refined everyday boxer briefs with a smooth waistband and soft cotton feel.", "colors": "Black / Grey / Navy", "image": "assets/images/products/essential-boxer-briefs.jpg"}, {"name": "Classic Briefs", "category": "briefs", "price": "$34.99", "description": "Clean-cut briefs designed for a close fit and easy everyday wear.", "colors": "White / Charcoal / Navy", "image": "assets/images/products/classic-briefs.jpg"}, {"name": "Modal Trunks", "category": "trunks", "price": "$29.99", "description": "Soft modal trunks with a streamlined silhouette and lightweight stretch.", "colors": "Navy / Black / Grey", "image": "assets/images/products/modal-trunks.jpg"}, {"name": "V-Neck Undershirts (3-Pack)", "category": "base-layers", "price": "$42.00", "description": "Smooth V-neck base layers designed to sit cleanly beneath shirts.", "colors": "White / Black / Grey", "image": "assets/images/products/v-neck-undershirts.jpg"}, {"name": "Boxer Duo Set", "category": "boxers", "price": "$36.00", "description": "A two-piece everyday boxer set built around clean lines and comfort.", "colors": "Black / Charcoal", "image": "assets/images/products/boxer-duo.jpg"}, {"name": "Classic White Brief", "category": "briefs", "price": "$24.00", "description": "A timeless white brief with a minimal premium finish.", "colors": "White", "image": "assets/images/products/white-brief.jpg"}, {"name": "Soft Grey Trunk", "category": "trunks", "price": "$26.00", "description": "A versatile grey trunk with a soft hand feel and flexible construction.", "colors": "Heather Grey", "image": "assets/images/products/grey-trunk.jpg"}, {"name": "Everyday Base Layer Set", "category": "base-layers", "price": "$39.00", "description": "Essential fitted layers for a clean wardrobe foundation.", "colors": "Black / White / Grey", "image": "assets/images/products/base-layer-set.jpg"}, {"name": "Premium Sock Trio", "category": "socks", "price": "$24.99", "description": "A refined trio of everyday socks in neutral shades.", "colors": "Black / White / Grey", "image": "assets/images/products/sock-trio.jpg"}, {"name": "Tailored Lounge Short", "category": "lounge", "price": "$32.99", "description": "Relaxed lounge shorts with a polished silhouette and soft finish.", "colors": "Charcoal", "image": "assets/images/products/lounge-short.jpg"}, {"name": "Signature Gift Box", "category": "gift-sets", "price": "$49.99", "description": "A curated essentials set prepared for effortless gifting.", "colors": "Black / Ivory", "image": "assets/images/products/signature-gift.jpg"}, {"name": "Performance Trunk", "category": "performance", "price": "$36.99", "description": "Breathable performance-focused trunk for active everyday comfort.", "colors": "Black / Navy", "image": "assets/images/products/performance-trunk.jpg"}];
let cart=JSON.parse(localStorage.getItem('veran-cart')||'[]');
function saveCart(){localStorage.setItem('veran-cart',JSON.stringify(cart));renderCart()}
function addToCart(i){const p=PRODUCTS[i],f=cart.find(x=>x.name===p.name);if(f)f.qty++;else cart.push({...p,qty:1});saveCart();openCart()}
function removeFromCart(i){cart.splice(i,1);saveCart()}
function openCart(){document.querySelector('#cart').classList.add('open')}
function closeCart(){document.querySelector('#cart').classList.remove('open')}
function closeModal(){document.querySelector('#modal').classList.remove('open')}
function renderCart(){const el=document.querySelector('#cartItems');if(!el)return;el.innerHTML=cart.length?cart.map((p,i)=>`<div class="cart-item"><img src="${p.image}" alt=""><div><strong>${p.name}</strong><div>${p.price} × ${p.qty}</div></div><button onclick="removeFromCart(${i})">×</button></div>`).join(''):'<p>Your bag is empty.</p>';const n=cart.reduce((a,x)=>a+x.qty,0);document.querySelectorAll('#cartCount').forEach(x=>x.textContent=n)}
function quickView(i){const p=PRODUCTS[i];const root=location.pathname.includes('/pages/')?'../':'';document.querySelector('#modalContent').innerHTML=`<img src="${root}${p.image}" alt="${p.name}"><div><div class="tag">${p.category.replace('-',' ')}</div><h2>${p.name}</h2><p>${p.description}</p><div class="price">${p.price}</div><p><strong>Tones:</strong> ${p.colors}</p><button class="btn" onclick="addToCart(${i});closeModal()">Add to bag</button></div>`;document.querySelector('#modal').classList.add('open')}
function card(p,i){const root=location.pathname.includes('/pages/')?'../':'';return `<article class="product-card"><img src="${root}${p.image}" alt="${p.name}" loading="lazy"><div class="product-copy"><div class="tag">${p.category.replace('-',' ')}</div><h3>${p.name}</h3><p>${p.description}</p><div class="price">${p.price}</div><div class="product-actions"><button class="add" onclick="addToCart(${i})">Add to bag</button><button class="save" onclick="this.textContent=this.textContent==='♡'?'♥':'♡'">♡</button><button class="save" onclick="quickView(${i})">View</button></div></div></article>`}
function renderShop(){const el=document.querySelector('#shopGrid');if(!el)return;const q=(document.querySelector('#search')?.value||'').toLowerCase(),c=document.querySelector('#category')?.value||'';let a=PRODUCTS.filter(p=>(!q||p.name.toLowerCase().includes(q))&&(!c||p.category===c));const s=document.querySelector('#sort')?.value;if(s==='low')a.sort((x,y)=>parseFloat(x.price.slice(1))-parseFloat(y.price.slice(1)));if(s==='high')a.sort((x,y)=>parseFloat(y.price.slice(1))-parseFloat(x.price.slice(1)));el.innerHTML=a.map(p=>card(p,PRODUCTS.indexOf(p))).join('')}
function renderFeatured(){const el=document.querySelector('#featured');if(el)el.innerHTML=PRODUCTS.slice(0,8).map((p,i)=>card(p,i)).join('')}
document.addEventListener('DOMContentLoaded',()=>{renderFeatured();renderShop();renderCart()})
